@startuml
' skinparam backgroundColor transparent

actor Alice as alice
participant "\nIssuer\n" as  issuer
actor Bob as bob

issuer --> issuer: create CDDC
rnote right of issuer: CDDC
issuer --> issuer: create MKCs
rnote right of issuer: MKCs


alice->issuer: RequestCDDCSerial
issuer->alice: ResponseCDDCSerial
rnote right of alice: CDD serial

alice->issuer: RequestCDDC
issuer->alice:  ResponseCDDC
rnote right of alice: CDDC

alice->issuer: RequestMKCs
issuer->alice: ResponseMKCs
rnote right of alice: MKCs

bob-->bob: also fetch\nissuer documents
rnote right of bob: CDDC\nMKCs

alice --> alice: prepare blinds
rnote left of alice: Payloads\nBlinds\n-\nblinding factors

alice -> issuer: RequestMint
rnote left of issuer: Blinds

issuer --> issuer: sign blinds

issuer -> alice: ResponseMint
rnote right of alice: BlindSignatures

alice --> alice: unblind
rnote left of alice: Coins

alice -> bob: transfer, e.g. using Signal
rnote left of bob: CoinStack
rnote right of bob: Coins

bob --> bob: tokenize

bob --> bob: prepare blinds
rnote right of bob: Payloads\nBlinds\n-\nblinding factors

bob -> issuer: RequestRenew
rnote right of issuer: Coins\nBlinds

opt Some Delay
    issuer -> bob: ResponseDelay
    bob -> issuer: RequestResume
end

issuer-->issuer: validate coins
issuer --> issuer: sign blinds
issuer -> bob: ResponseMint
rnote left of bob: BlindSignatures

bob --> bob: unblind
rnote right of bob: Coins

bob -> issuer: RequestRedeem
rnote right of issuer: Coins
issuer->bob: ResponseRedeem




@enduml