@startuml


actor Alice as alice
participant "\nIssuer\n" as  issuer
actor Bob as bob

issuer --> issuer: create CDDC
rnote right of issuer: CDDC
issuer --> issuer: create MKCs
rnote right of issuer: MKCs


alice->issuer: 1. RequestCDDSerial
issuer->alice: ResponseCDDSerial
rnote right of alice: cdd_serial: 1

alice->issuer: 2. RequestCDDC
issuer->alice:  ResponseCDDC
rnote right of alice: CDDC

alice->issuer: 3. RequestMKCs
issuer->alice: ResponseMKCs
rnote right of alice: MKCs

bob-->bob: also fetch\n issuer documents
rnote right of bob: CDDC\nMKCs

alice --> alice: prepare blinds
rnote left of alice: Payloads\nBlinds\n-\nblinding factors

alice -> issuer: 4. RequestMint
rnote left of issuer: Blinds

issuer --> issuer: sign blinds

issuer -> alice: ResponseMint
rnote right of alice: BlindSignatures

alice --> alice: unblind
rnote left of alice: Coins

alice -> bob: transfer CoinStack, e.g. using Signal
rnote left of bob: Coinstack
rnote right of bob: Coins

bob --> bob: tokenize sum

bob --> bob: prepare blinds
rnote right of bob: Payloads\nBlinds\n-\nblinding factors

bob -> issuer: 5. RequestRenew
rnote right of issuer: Coins\nBlinds

opt Some Delay
    issuer -> bob: ResponseDelay
    bob -> issuer: 6. RequestResume
end

issuer-->issuer: validate coins
issuer --> issuer: sign blinds
issuer -> bob: ResponseMint
rnote left of bob: BlindSignatures

bob --> bob: unblind
rnote right of bob: Coins

bob -> issuer: 7. RequestRedeem
rnote right of issuer: Coins
issuer->bob: ResponseRedeem




@enduml